swagger: "2.0"
info:
  version: 1.0.0
  title: Proxy PagoPA
  description: Proxy for PagoPA payment services
basePath: /api/v1
schemes:
  - https
paths:
  "/payment-requests/{rptId}":
    x-swagger-router-controller: PaymentController
    get:
      operationId: paymentRequestsGet
      summary: Get Payment Info
      description: Retrieve information about a payment
      parameters:
        - name: rptId
          in: path
          required: true
          schema:
            $ref: "#/definitions/RptId"
      responses:
        '200':
          description: Payment information retrieved
          schema:
            "$ref": "#/definitions/PaymentRequestsGetResponse"
          examples:
            application/json:
              importoSingoloVersamento: 200,
              codiceContestoPagamento: "ABC123"
        "400":
          description: Input provided or pagoPA response are invalid
        "500":
          description: PagoPA services are not available or request is rejected
  "/payment-activations":
    x-swagger-drouter-controller: PaymentController
    post:
      operationId: paymentActivationsPost
      summary: Activate Payment
      description: Require a lock (activation) for a payment
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/PaymentActivationsPostRequest"
          x-examples:
            application/json:
              rptId: "112345678901234556"
              importoSingoloVersamento: 200
              codiceContestoPagamento: "ABC123"
      responses:
        '200':
          description: It confirm that payment activation process started
          schema:
            "$ref": "#/definitions/PaymentActivationsPostResponse"
          examples:
            application/json:
              importoSingoloVersamento: 200
        "400":
          description: Input provided or PagoPA response are invalid
        "500":
          description: PagoPA services are not available or request is rejected
  "/payment-activations/{codiceContestoPagamento}":
    x-swagger-router-controller: PaymentController
    get:
      operationId: paymentActivationsGet
      summary: Check Activation status
      description: Check the activation status to retrieve the paymentId
      parameters:
        - name: codiceContestoPagamento
          in: path
          required: true
          description: The transaction id for PagoPA
          schema:
            $ref: "#/definitions/CodiceContestoPagamento"
      responses:
        '200':
          description: Payment information retrieved
          schema:
            $ref: "#/definitions/PaymentActivationsGetResponse"
          examples:
            application/json:
              idPagamento: "XYZ123234234"
        "400":
          description: Input provided is invalid
        "500":
          description: Activation status is not available
definitions:
  CodiceContestoPagamento:
    description: Transaction Id used to identify the communication flow
    type: string
    minLength: 1
    maxLength: 35
  EnteBeneficiario:
    description: Beneficiary institution related to a payment
    type: object
    properties:
      identificativoUnivocoBeneficiario:
        type: string
        minLength: 1
        maxLength: 35
      denominazioneBeneficiario:
        type: string
        minLength: 1
        maxLength: 70
      codiceUnitOperBeneficiario:
        type: string
        minLength: 1
        maxLength: 35
      denomUnitOperBeneficiario:
        type: string
        minLength: 1
        maxLength: 70
      indirizzoBeneficiario:
        type: string
        minLength: 1
        maxLength: 70
      civicoBeneficiario:
        type: string
        minLength: 1
        maxLength: 16
      capBeneficiario:
        type: string
        minLength: 1
        maxLength: 16
      localitaBeneficiario:
        type: string
        minLength: 1
        maxLength: 35
      provinciaBeneficiario:
        type: string
        minLength: 1
        maxLength: 35
      nazioneBeneficiario:
        type: string
        pattern: "[A-Z]{2,2}"
    required:
      - identificativoUnivocoBeneficiario
      - denominazioneBeneficiario
      - codiceUnitOperBeneficiario
      - denomUnitOperBeneficiario
      - indirizzoBeneficiario
      - civicoBeneficiario
      - capBeneficiario
      - localitaBeneficiario
      - provinciaBeneficiario
      - nazioneBeneficiario
  Iban:
    type: string
    pattern: "[a-zA-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}"
  Importo:
    description: Amount for payments
    type: number
    minimum: 0.11
    maximum: 999999.99
  PaymentActivationsGetResponse:
    type: object
    description: Define the response to send to App to provide the payment activation status related to a codiceContestoPagamento
    properties: 
      idPagamento:
        type: string
        minLength: 1
        maxLength: 35
    required:
    - idPagamento
  PaymentActivationsPostRequest:
    type: object
    description: Define the request received from CD App to require a payment activation
    properties:
      rptId:
        $ref: "#/definitions/RptId"
      importoSingoloVersamento:
        $ref: "#/definitions/Importo"
      codiceContestoPagamento:
        $ref: "#/definitions/CodiceContestoPagamento"
    required:
      - rptId
      - importoSingoloVersamento
      - codiceContestoPagamento
  PaymentActivationsPostResponse:
    type: object
    description: Define the response to send to CD App containing payment information
    properties:      
      importoSingoloVersamento:
        $ref: "#/definitions/Importo"
      ibanAccredito:
        $ref: "#/definitions/Iban"
      causaleVersamento:
        type: string
        minLength: 1
        maxLength: 140
      enteBeneficiario:
        $ref: "#/definitions/EnteBeneficiario"
      spezzoniCausaleVersamento:
        $ref: "#/definitions/SpezzoniCausaleVersamento"
    required:
    - importoSingoloVersamento
  PaymentRequestsGetResponse:
    type: object
    title: PaymentRequestsGetResponse
    description: Define the response to send to CD App containing payment information
    properties:
      importoSingoloVersamento:
        $ref: "#/definitions/Importo"
      codiceContestoPagamento:
        $ref: "#/definitions/CodiceContestoPagamento"
      ibanAccredito:
        $ref: "#/definitions/Iban"
      causaleVersamento:
        type: string
        minLength: 1
        maxLength: 140
      enteBeneficiario:
        $ref: "#/definitions/EnteBeneficiario"
      spezzoniCausaleVersamento:
        $ref: "#/definitions/SpezzoniCausaleVersamento"
    required:
      - importoSingoloVersamento
      - codiceContestoPagamento
  RptId:
    type: string
  SpezzoniCausaleVersamento: 
    description: Payment installments (optional)
    type: array
    items:
      $ref: "#/definitions/SpezzoniCausaleVersamentoItem"
  SpezzoniCausaleVersamentoItem:
    description: Single element of a payment installments
    type: object
    properties:
      spezzoneCausaleVersamento:
        type: string
        minLength: 1
        maxLength: 35
      spezzoneStrutturatoCausaleVersamento:
        $ref: "#/definitions/SpezzoneStrutturatoCausaleVersamento"
  SpezzoneStrutturatoCausaleVersamento:
    description: Amount related to a single element of a payment installments
    type: object
    properties:
      causaleSpezzone:
        type: string
        minLength: 1
        maxLength: 25
      importoSpezzone:
        $ref: "#/definitions/Importo"                      
consumes:
  - application/json
produces:
  - application/json